In [1]:
import numpy as np

In [3]:
X = np.arange(1, 26).reshape(5, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.dot(X, ones)

array([[ 15.,  15.,  15.,  15.,  15.],
       [ 40.,  40.,  40.,  40.,  40.],
       [ 65.,  65.,  65.,  65.,  65.],
       [ 90.,  90.,  90.,  90.,  90.],
       [115., 115., 115., 115., 115.]])

In [6]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
zerosDiag = np.zeros((5,5))
np.fill_diagonal(zerosDiag, 1)
zerosDiag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.dot(X, zerosDiag)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [18]:
np.where(X > 10, 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
np.where(X % 2 == 0, 1, 0)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [20]:
np.where(X % 2 == 0, X, X+1)

array([[ 2,  2,  4,  4,  6],
       [ 6,  8,  8, 10, 10],
       [12, 12, 14, 14, 16],
       [16, 18, 18, 20, 20],
       [22, 22, 24, 24, 26]])

In [21]:
X_bis = np.where(X > 10, X*2, 0)
X_bis

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [22]:
np.count_nonzero(X_bis)

15

In [23]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

In [24]:
np.append(x, y, axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [25]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100, 200, 300]])

In [27]:
np.append(x, y, axis=0)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300]])

In [28]:
np.append(np.append(x, y, axis=0), x, axis=0)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300],
       [ 10,  20,  30],
       [ 40,  50,  60]])