In [1]:
import numpy as np

In [2]:
X = np.arange(-25, 25, 1).reshape(10, 5)
X

array([[-25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [3]:
ones = np.ones((10,1))
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [4]:
X_1 = np.append(X, ones, axis=1)
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [8]:
w = np.random.rand(len(X_1[0,:]))
w

array([0.55669213, 0.81631454, 0.92161846, 0.35909129, 0.68239541,
       0.55711097])

In [9]:
def predict(x, w):
    total_stimulation = np.dot(x, w)
    if total_stimulation >= 0:
        return 1
    else:
        return -1

In [10]:
predict(X_1[0, :], w)

-1

In [11]:
for i in X_1:
    print(predict(i, w))

-1
-1
-1
-1
-1
1
1
1
1
1
