In [1]:
import numpy as np

In [3]:
X = np.arange(-25, 25, 1).reshape(10, 5)
ones = np.ones((10,1))
X_1 = np.append(X, ones, axis=1)
w = np.random.rand(len(X_1[0,:]))

In [4]:
def predict(x, w):
    total_stimulation = np.dot(x, w)
    if total_stimulation >= 0:
        return 1
    else:
        return -1

In [5]:
y = np.array([1, -1, -1, 1, -1, 1, -1, -1, 1, -1])
eta = 0.01

In [6]:
for x, y_target in zip(X_1, y):
    y_pred = predict(x, w)
    delta_w = eta*(y_target - y_pred)*x
    w += delta_w
    print(w)

[ 4.53043111e-04  2.86045208e-02  4.54357241e-01 -2.12597457e-01
  5.69304512e-01  8.58647524e-01]
[ 4.53043111e-04  2.86045208e-02  4.54357241e-01 -2.12597457e-01
  5.69304512e-01  8.58647524e-01]
[ 4.53043111e-04  2.86045208e-02  4.54357241e-01 -2.12597457e-01
  5.69304512e-01  8.58647524e-01]
[-0.19954696 -0.15139548  0.29435724 -0.35259746  0.44930451  0.87864752]
[-0.09954696 -0.07139548  0.35435724 -0.31259746  0.46930451  0.85864752]
[-0.09954696 -0.07139548  0.35435724 -0.31259746  0.46930451  0.85864752]
[-0.19954696 -0.19139548  0.21435724 -0.47259746  0.28930451  0.83864752]
[-0.19954696 -0.19139548  0.21435724 -0.47259746  0.28930451  0.83864752]
[ 0.10045304  0.12860452  0.55435724 -0.11259746  0.66930451  0.85864752]
[-0.29954696 -0.29139548  0.11435724 -0.57259746  0.18930451  0.83864752]


In [7]:
epochs = 10
for i in range(epochs):
    for x, y_target in zip(X_1, y):
        y_pred = predict(x, w)
        delta_w = eta*(y_target - y_pred)*x
        w += delta_w
        print(w)
    print('\n', 10*'--', '\n')

[-0.29954696 -0.29139548  0.11435724 -0.57259746  0.18930451  0.83864752]
[ 0.10045304  0.08860452  0.47435724 -0.23259746  0.50930451  0.81864752]
[ 0.10045304  0.08860452  0.47435724 -0.23259746  0.50930451  0.81864752]
[-0.09954696 -0.09139548  0.31435724 -0.37259746  0.38930451  0.83864752]
[ 4.53043111e-04 -1.13954792e-02  3.74357241e-01 -3.32597457e-01
  4.09304512e-01  8.18647524e-01]
[ 4.53043111e-04 -1.13954792e-02  3.74357241e-01 -3.32597457e-01
  4.09304512e-01  8.18647524e-01]
[-0.09954696 -0.13139548  0.23435724 -0.49259746  0.22930451  0.79864752]
[-0.09954696 -0.13139548  0.23435724 -0.49259746  0.22930451  0.79864752]
[ 0.20045304  0.18860452  0.57435724 -0.13259746  0.60930451  0.81864752]
[-0.19954696 -0.23139548  0.13435724 -0.59259746  0.12930451  0.79864752]

 -------------------- 

[-0.19954696 -0.23139548  0.13435724 -0.59259746  0.12930451  0.79864752]
[ 0.20045304  0.14860452  0.49435724 -0.25259746  0.44930451  0.77864752]
[ 0.20045304  0.14860452  0.49435724 