In [1]:
import numpy as np
 
data = np.array([[10, 7, 4], [3, 2, 1]])
data

array([[10,  7,  4],
       [ 3,  2,  1]])

In [2]:
data.mean()

4.5

In [3]:
data.mean(axis=0)

array([6.5, 4.5, 2.5])

In [4]:
data.mean(axis=1)

array([7., 2.])

In [5]:
np.average(data)

4.5

In [8]:
np.average(data, 0, [0,1])

array([3., 2., 1.])

In [10]:
np.average(data, 1, [1,1,0])

array([8.5, 2.5])

In [11]:
data.var()

9.583333333333334

In [12]:
data.var(axis = 0)

array([12.25,  6.25,  2.25])

In [13]:
data.std()

3.095695936834452

In [14]:
data.std(axis=1)

array([2.44948974, 0.81649658])

In [15]:
data = np.zeros((2, 1000000))
data[0, :] = 1.0
data[1, :] = 0.1
np.mean(data, dtype=np.float32)
np.mean(data, dtype=np.float64)

0.5499999999999972

In [16]:
data = np.zeros((2, 10))
data[0, :] = 1.0
data[1, :] = 0.1
np.mean(data, dtype=np.float32)
np.mean(data, dtype=np.float64)

0.55