In [3]:
import numpy as np

In [5]:
rand_a = np.random.rand()
rand_a

0.5016989619106657

In [6]:
rand_a = np.random.rand(2,5)
rand_a

array([[0.92114429, 0.35873525, 0.47277243, 0.73704963, 0.45020687],
       [0.06123299, 0.07296105, 0.97950994, 0.31001073, 0.41663193]])

In [7]:
rand_b = np.random.rand(1,5)
rand_b

array([[0.24427404, 0.17405929, 0.34989569, 0.29660464, 0.04608677]])

In [8]:
rand_b = rand_b * 100
rand_b

array([[24.42740367, 17.40592949, 34.98956931, 29.66046436,  4.60867691]])

In [10]:
rand_c = np.vstack([rand_a, rand_b])
rand_c

array([[ 0.92114429,  0.35873525,  0.47277243,  0.73704963,  0.45020687],
       [ 0.06123299,  0.07296105,  0.97950994,  0.31001073,  0.41663193],
       [24.42740367, 17.40592949, 34.98956931, 29.66046436,  4.60867691]])

In [11]:
rand_b = np.random.rand(2,1)
rand_b

array([[0.77658186],
       [0.6255875 ]])

In [12]:
rand_c = np.hstack([rand_a, rand_b])
rand_c

array([[0.92114429, 0.35873525, 0.47277243, 0.73704963, 0.45020687,
        0.77658186],
       [0.06123299, 0.07296105, 0.97950994, 0.31001073, 0.41663193,
        0.6255875 ]])

In [13]:
X = rand_c[:, 1]
X

array([0.35873525, 0.07296105])

In [14]:
a = 3
b = 8
y = a * X + b

In [15]:
y

array([9.07620574, 8.21888316])

In [16]:
X = np.random.randint(size=10, low=0, high=10)
X

array([2, 6, 1, 5, 8, 7, 5, 8, 3, 6])

In [57]:
X = X*10
X

array([20, 60, 10, 50, 80, 70, 50, 80, 30, 60])

In [116]:
np.random.choice(X, size=3)

array([80, 80, 80])

In [140]:
idx = np.random.choice(X.shape[0], size=3, replace=False)
idx

array([6, 3, 9])

In [141]:
X[idx]

array([50, 50, 60])