In [66]:
import numpy as np

In [67]:
a = np.arange(0, 20, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
a.shape

(20,)

In [69]:
a[0]

0

In [70]:
a[4]

4

In [71]:
a = a.reshape(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [72]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[0,0]

0

In [74]:
a[0,4]

4

In [75]:
a=a.reshape(2,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [76]:
a.shape

(2, 5, 2)

In [77]:
a[0]
# pierwsza płaszczyzna

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [78]:
a[0, 3, :]
# czwarty wiersz 1 płaszczyzny

array([6, 7])

In [79]:
a[0, 3, 1]
# 2 elememt (kolumna) czwartego wiersza na pierwszej plaszczzyznie

7

In [80]:
b = np.arange(2, 41, 2).reshape(4,5)

In [81]:
c = np.array([2**x for x in range(10)])

In [82]:
zero_array = np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
one_array = np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [84]:
empty_array = np.empty(100)
empty_array

array([0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 6.95308940e-310,
       4.69362364e-322, 1.01113548e-311, 1.01113548e-311, 1.01113548e-311,
       1.01113548e-311, 1.01113548e-311, 1.01113548e-311, 1.01113548e-311,
       1.01113548e-311, 1.01113549e-311, 1.01113548e-311, 1.01113548e-311,
       1.01113548e-311, 1.01113548e-311, 1.01113548e-311, 1.01113549e-311,
       1.01113549e-311, 1.01113549e-311, 1.01113548e-311, 1.01113549e-311,
       1.01113548e-311, 1.01113548e-311, 1.01113548e-311, 1.01113549e-311,
       1.01113142e-311, 1.01113142e-311, 1.01113142e-311, 1.01113142e-311,
       1.01113142e-311, 1.01113142e-311, 1.01113142e-311, 1.01113142e-311,
       1.01113142e-311, 1.01113142e-311, 1.01113142e-311, 1.01113142e-311,
       1.01113142e-311, 1.01113142e-311, 1.01113142e-311, 1.01113142e-311,
       1.01113142e-311, 1.01113142e-311, 1.01113142e-311, 1.01113142e-311,
       1.01113576e-311, 1.01113576e-311, 1.01113575e-311, 1.01113576e-311,
       1.01113576e-311, 1

In [87]:
lucky_array = np.full((5,5), 13)
lucky_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [88]:
diagonal_array = np.eye(5, 5)
diagonal_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [91]:
random_array = np.random.random(10)
random_array

array([0.29631914, 0.8452807 , 0.84288959, 0.21217324, 0.18820197,
       0.68046371, 0.05191391, 0.08052378, 0.38786143, 0.45759318])

In [93]:
linspace_array = np.linspace(100, 200, 5)
linspace_array

array([100., 125., 150., 175., 200.])