In [3]:
import numpy as np

In [4]:
arr = np.arange(5, 30, 2)
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [5]:
arr < 10

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [6]:
boolArr = arr < 10
boolArr

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [7]:
arr[boolArr]

array([5, 7, 9])

In [8]:
arr[arr < 20]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
arr[arr % 3 == 0]

array([ 9, 15, 21, 27])

In [10]:
arr[(arr > 10) & (arr < 20)]

array([11, 13, 15, 17, 19])

In [11]:
newArray = np.arange(0, 24)
newArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
newArray = newArray.reshape(4,6)
newArray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
newArray[1,:]

array([ 6,  7,  8,  9, 10, 11])

In [17]:
newArray[1, 2]

8

In [19]:
newArray[1,2:4]

array([8, 9])

In [20]:
newArray[1,2:5]

array([ 8,  9, 10])

In [21]:
newArray[1]

array([ 6,  7,  8,  9, 10, 11])

In [23]:
newArray[0:3, 2]

array([ 2,  8, 14])

In [24]:
newArray[:2, 2]

array([2, 8])

In [25]:
newArray[:2, 2:4]

array([[2, 3],
       [8, 9]])

In [26]:
newArray[:, -1]

array([ 5, 11, 17, 23])

In [27]:
newArray[:, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [28]:
anotherArr = np.arange(0,50).reshape(10,5)
anotherArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [29]:
split_ratio = 0.2
n_of_rows = anotherArr.shape[0]
split_border = split_ratio * n_of_rows

In [30]:
anotherArr[:round(split_border), :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
anotherArr[round(split_border):, :]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
np.random.shuffle(anotherArr)

In [37]:
anotherArr

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44]])

In [38]:
anotherArr[:round(split_border), :]

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29]])

In [39]:
anotherArr[round(split_border):, :]

array([[35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [40, 41, 42, 43, 44]])

In [40]:
data = np.arange(500).reshape(100,5)

In [43]:
def split_for_ml(data, ratio):
    border = round(ratio * data.shape[0])
    np.random.shuffle(data)
    X = data[:, :-1]
    y = data[:, -1]
    X_train = X[border:, :]
    X_test = X[:border, :]
    y_train = y[border:]
    y_test = y[:border]
    return X_train, X_test, y_train, y_test

In [44]:
print(split_for_ml(data, 0.2))

(array([[ 15,  16,  17,  18],
       [ 35,  36,  37,  38],
       [ 25,  26,  27,  28],
       [445, 446, 447, 448],
       [120, 121, 122, 123],
       [ 75,  76,  77,  78],
       [440, 441, 442, 443],
       [465, 466, 467, 468],
       [380, 381, 382, 383],
       [210, 211, 212, 213],
       [400, 401, 402, 403],
       [ 90,  91,  92,  93],
       [355, 356, 357, 358],
       [180, 181, 182, 183],
       [215, 216, 217, 218],
       [ 95,  96,  97,  98],
       [ 45,  46,  47,  48],
       [ 70,  71,  72,  73],
       [175, 176, 177, 178],
       [ 40,  41,  42,  43],
       [450, 451, 452, 453],
       [190, 191, 192, 193],
       [ 55,  56,  57,  58],
       [420, 421, 422, 423],
       [150, 151, 152, 153],
       [205, 206, 207, 208],
       [335, 336, 337, 338],
       [370, 371, 372, 373],
       [125, 126, 127, 128],
       [260, 261, 262, 263],
       [195, 196, 197, 198],
       [365, 366, 367, 368],
       [375, 376, 377, 378],
       [ 50,  51,  52,  53],
       [265, 